# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5220727b7026ea3462d1249e9853e2a608181967d35af5e819f3be5e9072077b5715970ed13b322f731755a55e7a0687e9ac34a32f11dac1d22079c3e42bd8a2

test:
  secret_key_base: 818e3f60234a651203b0b249ebcf62f0d435b05063b1b4aae6df27d4899e55c146e0ffb86f6bf44dfef91d3901da4250aad03e398153eaac6c313d02d6c4e50a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
